// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemadeGuarderias.Infrastructure;

#nullable disable

namespace SistemadeGuarderias.Infrastructure.Migrations
{
    [DbContext(typeof(SistemadeGuarderiasDbContext))]
    partial class SistemadeGuarderiasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemadeGuarderias.Domain.Entities.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuarderiaId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("GuarderiaId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("SistemadeGuarderias.Domain.Entities.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuarderiaId")
                        .HasColumnType("int");

                    b.Property<int>("NinoId")
                        .HasColumnType("int");

                    b.Property<bool>("Presente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GuarderiaId");

                    b.HasIndex("NinoId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("SistemadeGuarderias.Domain.Entities.Guarderia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("Guarderias");
                });

            modelBuilder.Entity("SistemadeGuarderias.Domain.Entities.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuarderiaId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("NinoId")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuarderiaId");

                    b.HasIndex("NinoId");

                    b.HasIndex("TutorId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("SistemadeGuarderias.Domain.Entities.Nino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActividadId")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("GuarderiaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("GuarderiaId");

                    b.HasIndex("Nombre");

                    b.HasIndex("TutorId");

                    b.ToTable("Ninos");
                });

            modelBuilder.Entity("SistemadeGuarderias.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuarderiaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NinoId")
                        .HasColumnType("int");

                    b.Property<bool>("Pagado")
                        .HasColumnType("bit");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuarderiaId");

                    b.HasIndex("NinoId");

                    b.HasIndex("TutorId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("SistemadeGuarderias.Domain.Entities.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("SistemadeGuarderias.Domain.Entities.Actividad", b =>
                {
                    b.HasOne("SistemadeGuarderias.Domain.Entities.Guarderia", "Guarderia")
                        .WithMany("Actividades")
                        .HasForeignKey("GuarderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guarderia");
                });

            modelBuilder.Entity("SistemadeGuarderias.Domain.Entities.Asistencia", b =>
                {
                    b.HasOne("SistemadeGuarderias.Domain.Entities.Guarderia", "Guarderia")
                        .WithMany("Asistencias")
                        .HasForeignKey("GuarderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeGuarderias.Domain.Entities.Nino", "Nino")
                        .WithMany("Asistencias")
                        .HasForeignKey("NinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guarderia");

                    b.Navigation("Nino");
                });

            modelBuilder.Entity("SistemadeGuarderias.Domain.Entities.Mensaje", b =>
                {
                    b.HasOne("SistemadeGuarderias.Domain.Entities.Guarderia", "Guarderia")
                        .WithMany("Mensajes")
                        .HasForeignKey("GuarderiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemadeGuarderias.Domain.Entities.Nino", "Nino")
                        .WithMany("Mensajes")
                        .HasForeignKey("NinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeGuarderias.Domain.Entities.Tutor", "Tutor")
                        .WithMany("Mensajes")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guarderia");

                    b.Navigation("Nino");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("SistemadeGuarderias.Domain.Entities.Nino", b =>
                {
                    b.HasOne("SistemadeGuarderias.Domain.Entities.Actividad", "Actividad")
                        .WithMany("Ninos")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemadeGuarderias.Domain.Entities.Guarderia", "Guarderia")
                        .WithMany("Ninos")
                        .HasForeignKey("GuarderiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemadeGuarderias.Domain.Entities.Tutor", "Tutor")
                        .WithMany("Ninos")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Guarderia");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("SistemadeGuarderias.Domain.Entities.Pago", b =>
                {
                    b.HasOne("SistemadeGuarderias.Domain.Entities.Guarderia", "Guarderia")
                        .WithMany("Pagos")
                        .HasForeignKey("GuarderiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemadeGuarderias.Domain.Entities.Nino", "Nino")
                        .WithMany("Pagos")
                        .HasForeignKey("NinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeGuarderias.Domain.Entities.Tutor", "Tutor")
                        .WithMany("Pagos")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guarderia");

                    b.Navigation("Nino");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("SistemadeGuarderias.Domain.Entities.Actividad", b =>
                {
                    b.Navigation("Ninos");
                });

            modelBuilder.Entity("SistemadeGuarderias.Domain.Entities.Guarderia", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Asistencias");

                    b.Navigation("Mensajes");

                    b.Navigation("Ninos");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("SistemadeGuarderias.Domain.Entities.Nino", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Mensajes");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("SistemadeGuarderias.Domain.Entities.Tutor", b =>
                {
                    b.Navigation("Mensajes");

                    b.Navigation("Ninos");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
